<?php

namespace TodolistBundle\Repository;

/**
 * todosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class todosRepository extends \Doctrine\ORM\EntityRepository
{
}
